export { default as Page404 } from './404';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Registration } from './Registration';
export { default as AboutUs } from './AboutUs';
export { default as Cart } from './Cart';
export { default as Catalog } from './Catalog';
export { default as User } from './User';
export { default as DetailedProduct } from './DetailedProduct';
